language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in wolfninja_keystore.pubring.gpg.enc
  -out wolfninja_keystore.pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in wolfninja_keystore.secring.gpg.enc
  -out wolfninja_keystore.secring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in gradle.properties.enc -out
  gradle.properties -d
script: gradle check javadoc
after_success:
- codecov
- .scripts/publish.sh
cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2
env:
  global:
    secure: TD3uLhisvHn6K8x4S9cz8V8UCj/DrUiebhulGqkvUmlRHS1qsbcVOvzEekUs5AizN5lW9xATmWkkzLUYC0MSzAavXRJjLZMgjF45WUa9Y8RwDCLVhlY5wHJkfnWehTsNFu00F+42V6fV4eucXulK2Nkip+EJY4sQvu8De/Aa2D9kmSmoyKu6c2o1PBAykDd2aGSNNEF2iks6X45aeYd7dxNhP75ecuK9UHo7bcU+qdqXmidspS/xmd2o3q31SfHdhLV0ls5C15wilcpn0Ng6brwvy5tQGLihf7BuQivsz6FASTSUWPhIOH0mkXMOz8qHsfbUhAaTRsuHEr3yin6Ip1kuUXC4eLyhVj/mT/yTejSUQ2BCjGjQZtAutuF3lRNMot4OfXmHTGWEwZRcHtxsAsG6Vc01pWM/R5eWxqj9HwBD25LivErKDUYu12rYcTc7ZkxqAVDww5qaWGHxhazGp2Jgou4MLwu3egNZovHaaR554Tz+gkoYyZLwcmXxxpCN+r7J+zDaxTMJnt2F2tKdVNdEVLMo7I2wnu027p7oYXRFZcKse1GjmB+CGel4D75p42MVOpR4UPI2TsgBKijkwp7RnygU6r3VzvjUyaF25iwWk1bA/Hvr9Goi1kMCXdniTbjw3sbPUmPfd3D3QzTeAPCdBlkcQHqlv/3e1VmKqu4=
